
stages: 
    - build
    - test
    - deploy
build-job:
  stage: build
  script: 
  - echo: "Compiling ready"
  -echo: "Compiling complete"

  unit-test-job:
    image: mcr.microsoft.com/playwright
    stage: test
    
    script:
      - npm ci
      - npx playwright install --with-deps
      - npx playwright test
    artefacts:
    - when: always
    - path: 
      - playwright-report/index.html
      # - echo: "Running tests."
      - sleep  60
      # - echo: "Code coverage is 90%."


deploy-job:
  stage: deploy
  script:
    - echo: "Deploying application"
    - echo: "Application succesfully deployed"

